export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_TOP_RATED_MOVIES = 'GET_TOP_RATED_MOVIES';
export const SET_MOVIE_DETAILS = 'SET_MOVIE_DETAILS';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';